const fileTypes = [
  {label: "JavaScript", value: "js"},
  {label: "TypeScript", value: "ts"},
  {label: "HTML", value: "html"},
  {label: "CSS", value: "css"},
  {label: "JSON", value: "json"},
  {label: "Text", value: "txt"},
  {label: "Python", value: "py"},
  {label: "Java", value: "java"},
  {label: "C", value: "c"},
  {label: "C++", value: "cpp"},
  {label: "C#", value: "cs"},
  {label: "Ruby", value: "rb"},
  {label: "PHP", value: "php"},
  {label: "Perl", value: "pl"},
  {label: "Shell Script", value: "sh"},
  {label: "Batch", value: "bat"},
  {label: "PowerShell", value: "ps1"},
  {label: "Kotlin", value: "kt"},
  {label: "Swift", value: "swift"},
  {label: "Go", value: "go"},
  {label: "Rust", value: "rs"},
  {label: "Lua", value: "lua"},
  {label: "R", value: "r"},
  {label: "MATLAB", value: "m"},
  {label: "Haskell", value: "hs"},
  {label: "Scala", value: "scala"},
  {label: "Objective-C", value: "m"},
  {label: "Dart", value: "dart"},
  {label: "Elixir", value: "ex"},
  {label: "Erlang", value: "erl"},
  {label: "SQL", value: "sql"},
  {label: "YAML", value: "yaml"},
  {label: "XML", value: "xml"},
  {label: "Markdown", value: "md"},
  {label: "INI", value: "ini"},
  {label: "TOML", value: "toml"},
  {label: "Config", value: "conf"},
  {label: "Dockerfile", value: "dockerfile"},
  {label: "Makefile", value: "makefile"},
  {label: "Gradle", value: "gradle"},
  {label: "CMake", value: "cmake"},
  {label: "Assembly", value: "asm"},
  {label: "Fortran", value: "f"},
  {label: "COBOL", value: "cob"},
  {label: "VBScript", value: "vbs"},
  {label: "VHDL", value: "vhd"},
  {label: "Verilog", value: "v"},
  {label: "Pascal", value: "pas"},
  {label: "Ada", value: "ada"},
  {label: "Prolog", value: "pl"},
  {label: "Lisp", value: "lisp"},
  {label: "Scheme", value: "scm"},
  {label: "Clojure", value: "clj"},
  {label: "F#", value: "fs"},
  {label: "OCaml", value: "ml"},
  {label: "Racket", value: "rkt"},
  {label: "Visual Basic", value: "vb"},
  {label: "Lua", value: "lua"},
  {label: "HCL", value: "hcl"},
  {label: "Log", value: "log"},
  {label: "Rich Text", value: "rtf"},
  {label: "Other", value: " "}
]

export default fileTypes;
